### ISSUE TITLE
oGdriveOOo & OAuthOOo usage

### ISSUE THREAD

**Issue by ghost** [prrvchr/gDriveOOo#1]
Firstly please accept my apology, but I am extremely new (as of yesterday) to GitHub and I have yet to figure out how to behave correctly.

Having said that, I am a new "converty" in that I have made a total transition from Microsoft to Linux incl. all 'standard tools' such as LibreOffice, Evolution (maybe Thunderbird don't know yet).

I have also made the transition from OneDrive to G-Suite, hence I may end up in deep s..t, but I'll give it a go anyway.

One thing I MUST have in place is how to access G-Suite drive from e.g. LibreOffice Version: 6.0.7.3, running on a LinuxMint (latest).

I have found your tool that, if I read it correctly, does exactly that.

I have managed to install OAuthOOo version 0.0.2 and also OGDRIVE OOo Version 0.0.1 - I have not been able to locate a newer version.

I can open my G-Suite, no problem, 
I can edit an existing file, no problem, 
I can save the same file, no problem, 
BUT, 
if I try to save with a new name OR create a new file it fails.

It seems that the oDriveOOo reads the 'google' internal name - a string of "random" numbers and letters".

**Setup**
Lenovo B560
LinuxMint 19.04
LibreOffice Version: 6.0.7.3
Build ID: 1:6.0.7-0ubuntu0.18.04.2
CPU threads: 2; OS: Linux 4.15; UI render: default; VCL: gtk3; 
Locale: en-US (en_US.UTF-8); Calc: group

I am not sure what I do wrong, but hope you can help.

**Comment by prrvchr** [comment]
Hi Kirenoid,

You are right and I apologize, but it is true that "Save As" does not work yet.
I have not found a solution running on OpenOffice and LibreOffice at the same time.
Offline mode, also not yet functional, I'm running out of time right now.

I take the opportunity to ask for help and invite anyone who knows Python to join the project ...

**Comment by prrvchr** [comment]
Hi Kirenoid,
I think I have fixed the malfunction.
It is also now possible to open Google documents...
I close the issue, but do not hesitate to open a new one if there is a problem.

**Comment by ghost** [comment]
Much appreciated, thank you. I will will test and let you know the outcome (good or not so good).

Best Regards and have a great weekend
Alex

Ha' en god dag
Alex

________________________________

**Comment by prrvchr** [comment]
Bonne journée à toi, aussi...
