### ISSUE TITLE
Libreoffice fails to connect

### ISSUE THREAD

**Issue by wiljaxon** [prrvchr/gDriveOOo#10]
For some reason, at the last stage of connecting I'm taken to this 'localhost' page: http://127.0.0.1:8080/?state=4d9268f63f904db59f6a235be2599cc9&code=4/0AX4XfWiDUYwBH6l1K31LcBUaVi43VD3wxc9tfRQdJawbKlDlVg1-_9ui2YxTzKLiPp1xUw&scope=https://www.googleapis.com/auth/drive. 

There was another server 'AIS dispatcher' which I removed, previously I was taken to it's login page. But after removing AIS Dispatcher, I see this message: "boost::filesystem::current_path: No such file or directory".

Boost is installed on my Ubuntu 20.04 computer. Any ideas? Much closer to connecting with Google Drive than before! Opening the 8080 port didn't help.

**Comment by prrvchr** [comment]
Hi wiljaxon,

Thank you for taking the time to open an issue, it helps me to improve the extension.

While waiting for the authorization OAuth2OOo listens for the response on the address: http://127.0.0.1:8080.

If during step 3 of the OAuth2OOo wizard, opening a page in the browser on the address: http://127.0.0.1:8080, does not redirect to the address: [The OAuth2OOo configuration failed](https://prrvchr.github.io/OAuth2OOo/source/OAuth2OOo/registration/OAuth2Error_en?user=youraccount%40gmail.com)

If so I think it could be:
- port 8080 is already occupied by an application...
- a firewall is blocking port 8080...

**Comment by prrvchr** [comment]
I consider that it was indeed a problem on port 8080 busy or blocked, I am closing accordingly...
