### ISSUE TITLE
Cannot add google account

### ISSUE THREAD

**Issue by erentar** [prrvchr/gDriveOOo#11]
I follow the steps as mentioned in the readme, although the gDriveOOo dialog crashes before allowing me to click "View Authentication".

Here is the log:
```
event no thread   date       time        (class/method:) message
1    31153 2022-11-19 22:59:24.585611873 OptionsDialog::_doClearLog(): ClearingLog ... Done
2    31153 2022-11-19 22:59:51.960514984 ContentProviderProxy::getContentProvider(): Need to get UCP: com.gmail.prrvchr.extensions.gDriveOOo ... Done
3    31153 2022-11-19 22:59:51.982429220 User::__init__(): User loading completed
4    31153 2022-11-19 23:00:05.197969302 User::__init__(): User loading completed
5    31153 2022-11-19 23:00:05.212796674 Identifier::__init__(): Identifier loading completed
6    31153 2022-11-19 23:00:05.219429620 ContentProvider::createContentIdentifier(): Identifier: vnd.google-apps://user@gmail.com/ ... Completed
7    31153 2022-11-19 23:00:05.225854092 ContentProviderProxy::getContentProvider(): Need to get UCP: com.gmail.prrvchr.extensions.gDriveOOo ... Done
8    31153 2022-11-19 23:00:05.232021217 ContentProvider::queryContent(): Identitifer: vnd.google-apps://user@gmail.com/ ... cannot be found: User: user@gmail.com does not exist at this Provider
```

**Comment by prrvchr** [comment]
Hi erentar,

Sorry for the delay, I didn't get a notification.

If not already fixed, it looks like the Google account user@gmail.com does not exist.

Make sure to use an existing Google account and reinstall the extensions in their latest version.

**Comment by erentar** [comment]
I tried everything you said, yet still the same issue.

**Comment by prrvchr** [comment]
Hi erentar,

If this problem is still relevant, can you give me your configuration (operating system, version of LibreOffice or OpenOffice and version of Java)

**Comment by prrvchr** [comment]
I just uploaded a new version with big changes and lots of fixes.
This allows me to close this issue...
