### ISSUE TITLE
Warning message in options panel.

### ISSUE THREAD

**Issue by mrplumber** [prrvchr/gDriveOOo#12]
My setup:

- Windows 10
- Java 17 Temurin
- LibreOffice 7.6.4.1
- Latest OAuth2OOo, jdbcDriverOOo, gDriveOOo

When choosing '_Remote then local_' Replication method In the gDriveOOo options panel, warning is shown (see attached screenshot below):
![EnabledSync_not_found](https://github.com/prrvchr/gDriveOOo/assets/15611917/62c1e8f6-adc8-4343-99e1-b6fe9919d06b)

Code search points to:
https://github.com/prrvchr/gDriveOOo/blob/0ea0d2a13a0804279edb52565d1205e8e3ba11c0/uno/dialog/ucb/OptionsDialog.xdl#L16

**Comment by prrvchr** [comment]
Hi mrplumber,

This defect has been corrected. You must now use gDriveOOo version 1.0.5.
It will require the version of OAuth2OOo 1.2.3 minimum.

Thank you for taking the time to report this malfunction. I'm waiting for you to confirm that it's working correctly in order to close this issue.
