### ISSUE TITLE
Extension does not actually save files on Google Drive.

### ISSUE THREAD

**Issue by mrplumber** [prrvchr/gDriveOOo#13]
My setup:

- Windows 10
- Java 17 Temurin
- LibreOffice 7.6.4.1
- Latest OAuth2OOo, jdbcDriverOOo, gDriveOOo

No matter what I do, files are not actually saved to my Google Drive, that is, files are not present when I look for them directly opening Google Drive in my Internet browser after I save them in LibreOffice.
Followed installation [procedures ](https://prrvchr.github.io/gDriveOOo/) to the letter.
Reinstalled extensions few times.
Tried two replication methods (_Remote then local_ and _Local then remote_).
To clarify, I can see, browse and open my Google Drive files and folders in _Open File_ dialogue which are already there. If I open, edit and save already present file, changes are not synced with Google Drive.

**Comment by prrvchr** [comment]
Hi mrplumber,

So it's strange because I just tested with the latest version with two different Google accounts and everything works perfectly for me. I can create and save files in LibreOffice.

Maybe you can give me more information. You can check the log files in: **Tools -> Options -> Internet -> gDriveOOo -> View log** (same for OAuth2OOo and jdbcDriverOOo).

**Comment by mrplumber** [comment]
Hi,

I reinstalled all three extensions, created new file _test15.ods_, "saved" (with the same result) it in my Goodle Drive using _vnd-google://..._ and collected the logs from extensions _OAuth2OOo_ and _gDriveOOo_. There are no options for extension _jdbcDriverOOo_. Please, see attached sanitized files.
[gDriveOOo_log_mrplumber.txt](https://github.com/prrvchr/gDriveOOo/files/13689965/gDriveOOo_log_mrplumber.txt)
[OAuth2OOo_log_mrplumber.txt](https://github.com/prrvchr/gDriveOOo/files/13689966/OAuth2OOo_log_mrplumber.txt)

**Comment by prrvchr** [comment]
Thanks for the logs.

~~I don't see any errors or abnormal activity.~~
Can you give the jdbcDriverOOo log in: **Tools -> Options -> Base drivers -> JDBC Driver -> View log** ?
Perhaps the problem comes from there since all replications are carried out from the database...

Edit: **Ok, I just found a problem in the replicator in log management**. I just updated without changing the version.
Can you try again, taking care to reinstall gDriveOOo

**Comment by mrplumber** [comment]
Reinstalled _gDriveOOo_ with new build.
Repeated the create-edit-save cycle with file _test16.ods_ - no success.
Collected logs for extension _gDriveOOo_ and _JDBC Driver_ (also attached screenshot of my settings for JDBC Driver)
[gDriveOOo_log_test16_mrplumber.txt](https://github.com/prrvchr/gDriveOOo/files/13690947/gDriveOOo_log_test16_mrplumber.txt)
[JDBC_Driver_log_test16_mrplumber.txt](https://github.com/prrvchr/gDriveOOo/files/13690948/JDBC_Driver_log_test16_mrplumber.txt)

![JDBC_Driver_settings_mrplumber](https://github.com/prrvchr/gDriveOOo/assets/15611917/cb01b15d-d34a-477a-a303-952018a6f29b)

**Comment by prrvchr** [comment]
The log file that must be consulted will be the log file of the gDriveOOo replicator. It is accessible in:
**Tools -> Options -> Internet -> gDriveOOo -> View log** but the **gDriveSync** (not gDriveLog).

If it is not activated, you must activate it and above all restart LibreOffice in order to see the replication activity.

**Comment by mrplumber** [comment]
New test with file _test17.ods_
[gDriveLog_test17_mrplumber.txt](https://github.com/prrvchr/gDriveOOo/files/13691151/gDriveLog_test17_mrplumber.txt)
[gDriveSync_log_test17_mrplumber.txt](https://github.com/prrvchr/gDriveOOo/files/13691152/gDriveSync_log_test17_mrplumber.txt)

**Comment by prrvchr** [comment]
Here are the logs that I get on I try to reproduce:

```
  event no thread   date       time        (class/method:) message
         1   156907 2023-12-16 03:30:04.438380735 DataBase::__init__(): DataBase: Loading completed
         2   157081 2023-12-16 03:30:16.518194882 Replicator::_synchronize(): Starting data synchronization at 2023-12-16T03:30:16.517772Z0
         3   157081 2023-12-16 03:30:16.622810484 Replicator::_pushUsers(): Starting data replication for user: prrvchr1@gmail.com at 2023-12-16T03:30:16.622499Z0
         4   157081 2023-12-16 03:30:19.632847607 Replicator::_pushItem(): Has replicated the creation of a file: Untitled 1.ods of 2023-12-16T03:30:16.000Z
         5   157081 2023-12-16 03:30:19.673698697 Replicator::_pushUsers(): End of replicating data for user: prrvchr1@gmail.com at 2023-12-16T03:30:19.673166Z0
         6   157081 2023-12-16 03:30:19.675644335 Replicator::_pullUsers(): Starting data download for user: prrvchr1@gmail.com at 2023-12-16T03:30:19.675379Z0
         7   157081 2023-12-16 03:30:20.206008289 Replicator::_pullUsers(): End of download for user: prrvchr1@gmail.com at 2023-12-16T03:30:20.205533Z0
         8   157081 2023-12-16 03:30:20.208147885 Replicator::_synchronize(): End of data synchronization at 2023-12-16T03:30:20.207785Z0
```

The problem is that I can't reproduce... I need to do more investigation

**Comment by mrplumber** [comment]
What version of LibreOffice are you running on your dev machine? Would it make sense for me to try switching to "stable" version 7.5.9?

**Comment by prrvchr** [comment]
my version is:

```
Version: 7.3.7.2 / LibreOffice Community
Build ID: 30(Build:2)
CPU threads: 2; OS: Linux 5.15; UI render: default; VCL: qt5 (cairo+xcb)
Locale: en-US (fr_FR.UTF-8); UI: en-US
Ubuntu package version: 1:7.3.7-0ubuntu0.22.04.3
Calc: threaded
```

But I just noticed a problem under Windows 10 (under Virtualbox).

I'm trying to find out more...

**Comment by prrvchr** [comment]
Hi mrplomber,

Ok, it took me quite a while but now I can get the same operation under Linux and Windows (under VirtualBox).

I just updated the versions of gDriveOOo 1.0.6, OAuth2OOo 1.2.4 and jdbcDriverOOo 1.0.8. Please update and keep me informed of any malfunctions.

I noted that a file updated in LibreOffice may take some time for the file modification to be visible in a browser opened on Google drive (ie: sometimes you have to refresh the Google drive page in the browser)

**Comment by prrvchr** [comment]
The new version 1.1.2 is available. This solves a multitude of problems. I'll let you try it and report any malfunctions.
