### ISSUE TITLE
gDriveOOo disables the native open/save dialog

### ISSUE THREAD

**Issue by M-Rick** [prrvchr/gDriveOOo#14]
When gDriveOOo is installed, the extension disables the native open/save dialog in LibreOffice.
The setting is locked and cannot be modified in the preferences. The only possibility to get the native GUI back is to remove the extension. The LibreOffice dialog is ugly and inconvenient to use.

<img width="894" alt="Capture d’écran 2024-05-02 à 00 28 58" src="https://github.com/prrvchr/gDriveOOo/assets/2520948/e0722782-9da0-4734-a36c-a00b239b25c6">

<img width="912" alt="Capture d’écran 2024-05-02 à 00 31 06" src="https://github.com/prrvchr/gDriveOOo/assets/2520948/19292a9e-255d-44ce-b6d2-b77bf77f4a59">

**Comment by prrvchr** [comment]
Hi M-Rick,

Two options are disabled in LibreOffice after installing gDriveOOo, they are:
- The native open/save dialog window.
- Creation of .bak files.

For now, there is no other choice than to uninstall the extension if you want to use one of these two options.
**But anyway the extension does not work if one of them is activated.**

**Comment by prrvchr** [comment]
Hi M-Rick,

Just to say that it is now possible to use the **native open/save dialog window** with the latest version of gDriveOOo. See [How to customize LibreOffice](https://prrvchr.github.io/gDriveOOo/#how-to-customize-libreoffice-menus) menus.
