### ISSUE TITLE
Can't use gDriveOOo on Ubuntu

### ISSUE THREAD

**Issue by jcvignoli** [prrvchr/gDriveOOo#15]
Hi,
Trying to run gDriveOOo on Ubuntu 22.04 with LibreOffice 7.3.7.2, but I fail. Running from console gives me the following error (French version):

```
Exception python inattendue avec le traceback: Traceback (most recent call last):
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 110, in queryContent
    content = self._datasource.queryContent(self, self._authority, url)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 97, in _datasource
    ContentProvider.__datasource = self._getDataSource()
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 163, in _getDataSource
    database = DataBase(self._ctx, self._logger, url)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/database.py", line 71, in __init__
    connection = getDataBaseConnection(ctx, url, user, pwd, new)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbinit.py", line 82, in getDataBaseConnection
    infos = getDriverInfos(ctx, url, g_drvinfos)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbtool/dbtool.py", line 807, in getDriverInfos
    for name, value in _getDriverPropertyInfo(ctx, location, properties, options):
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbtool/dbtool.py", line 814, in _getDriverPropertyInfo
    drivers = createService(ctx, service).createEnumeration()
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/unotool/unotool.py", line 344, in createService
    service = ctx.ServiceManager.createInstanceWithContext(name, ctx)
```

I try to open it using either vnd-google:/// or vnd-google://my.username@gmail.com, but I get in LibreOffice interface:

![Screenshot from 2024-10-24 16-46-31](https://github.com/user-attachments/assets/eee6d35a-fd39-4c14-9ff4-d9368642e13b)

I believe I installed all required LibreOffice plugins:

![Screenshot from 2024-10-24 16-47-56](https://github.com/user-attachments/assets/facdcbfa-7b1e-497a-ac40-5afac397045e)

I have a java jre:

![Screenshot from 2024-10-24 16-48-17](https://github.com/user-attachments/assets/a88e4803-2d1f-4c9c-a0ed-619997968bd0)

What am I missing?

Thanks!

**Comment by prrvchr** [comment]
Hi jcvignoli,

It seems to me that you are on Ubuntu and that you are using the version of LibreOffice provided with Ubuntu (ie: LibreOffice is installed via the package manager that Ubuntu offers).

If this is the case then you must ensure that the two packages (ie: `libreoffice-sdbc-hsqldb` and `libhsqldb1.8.0-java`) that install the Java archive of HsqlDB version 1.8.x **are not installed and uninstall them if necessary**.

More information on uninstalling these two packages is available in the [jdbcDriverOOo requirement](https://prrvchr.github.io/jdbcDriverOOo/#requirement).

**Comment by jcvignoli** [comment]
Thanks for your response.
I am indeed using LibreOffice provided by Ubuntu.
I should have reported, but I already checked if those two packages were installed:

```
Package 'libreoffice-sdbc-hsqldb' is not installed, so not removed
Package 'libhsqldb1.8.0-java' is not installed, so not removed

```
They weren't installed.

**Comment by prrvchr** [comment]
Is the HsqlDB version accessible in the options of the jdbcDriverOOo extension (ie: **Tools -> Options... -> LibreOffice Base -> Pilote JDBC pur Java -> Options des pilotes JDBC -> jdbc:hsqldb:***).

Normally it should be version 2.7.3 like this screenshot.

![version HsqlDB](https://github.com/user-attachments/assets/01c12e22-789e-400f-9249-b6a787468819)

**Comment by jcvignoli** [comment]
(francophone?)
I confirm I have hsqldb version 2.7.3 available.

**Comment by prrvchr** [comment]
On the other hand, I advise you to upgrade to version 24.x of LibreOffice, version 7.x is starting to get really old and strangely I can't get gDriveOOo to work under LibreOffice 7.3.7.2 while it works wonderfully under LibreOffice 24.2.1.2...

Under Ubuntu, it is possible to use LibreOffice PPA and the Ubuntu package manager to install this version (ie: `sudo add-apt-repository ppa:libreoffice/ppa` to add the PPA)

More information on this link: [LibreOffice 24.2 Available to Install via Ubuntu PPA](https://ubuntuhandbook.org/index.php/2024/03/libreoffice-24-2-ubuntu-ppa/)

**Comment by prrvchr** [comment]
Moreover, under LibreOffice 7.x if I try to open a file by **File -> Open** LibreOffice cannot even list the local files...

File open with LibreOffice 7.x:

![LibreOffice 7 x file open](https://github.com/user-attachments/assets/df935017-d82c-4cb5-9377-b644d09c583f)

File open with LibreOffice 24.x:

![LibreOffice 24 x file open](https://github.com/user-attachments/assets/0f83645b-3a75-4f2f-8094-50af3710abd8)

I can't explain this problem...


**EDIT:**  Well I found where it came from: I was missing the `libreoffice-qt5` package which is necessary because I am using Lubuntu (ie: lxqt).

**Comment by jcvignoli** [comment]
Hi,
I upated to LibreOffice version 24. Same issue.

**Comment by prrvchr** [comment]
It seems that the error is related to the failure to load the UNO service `com.sun.star.sdbc.DriverManager` needed when creating the gDriveOOo database.

To ensure this I have prepared a small BASIC macro to verify that it is possible to load the service in question.

```
Sub Main

    sTitle = "DriverManager UNO service test"

    Rem We try to load the UNO service: com.sun.star.sdbc.DriverManager
    oDriver = CreateUnoService("com.sun.star.sdbc.DriverManager")
    if isNull(oDriver) then
        Msgbox "ERROR: cannot instantiate UNO service: com.sun.star.sdbc.DriverManager!", 0, sTitle
    else
        Msgbox "UNO service: com.sun.star.sdbc.DriverManager has been loaded correctly", 0, sTitle
    endif

End Sub
```
It is possible by going through: **Tools -> Macros -> Edit macros** to copy and execute this piece of code in order to ensure the correct loading of the service.

**Comment by jcvignoli** [comment]
I guess you're right, the script stops at "oDriver = CreateUnoService("com.sun.star.sdbc.DriverManager")" and throws this error:

![Screenshot from 2024-10-25 20-10-57](https://github.com/user-attachments/assets/469f02ad-e77c-42ae-a226-a2d9bdd4c62a)

How can I fix it?

**Comment by prrvchr** [comment]
I get the same message (it took me a while) if I remove the `libreoffice-base-driver` packages.

![DriverManager error](https://github.com/user-attachments/assets/8cd79e97-ac98-4980-933b-b5225418e829)

Check that you have the package `libreoffice-base-driver` installed and if it is already installed then uninstall it and then reinstall it.

After you will have to remove the two hsqldb 1.8 packages (ie: `libreoffice-sdbc-hsqldb` and `libhsqldb1.8.0-java`) that will be added during the installation of `libreoffice-base-driver` .

**Comment by jcvignoli** [comment]
This time I get "UNO service: com.sun.star.sdbc.DriverManager has been loaded correctly", however, still getting same error message that "file doesn't exist" when opening "vnd-google:///"...

**Comment by prrvchr** [comment]
The problem is not the same anymore... I need more information...

Is this window displayed?

![OAuth2OOo window](https://github.com/user-attachments/assets/ee6a331d-18be-4033-861a-1ff47cc313e6)

Are there any messages in the console?

**Comment by jcvignoli** [comment]
I get the very same error message since my first report, it has never changed:
![379947902-eee6d35a-fd39-4c14-9ff4-d9368642e13b](https://github.com/user-attachments/assets/06d3fbd6-862c-4e72-a298-9026a16e4ea5)

**Comment by prrvchr** [comment]
No, the first message was this one:

```
Exception python inattendue avec le traceback: Traceback (most recent call last):
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 110, in queryContent
    content = self._datasource.queryContent(self, self._authority, url)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 97, in _datasource
    ContentProvider.__datasource = self._getDataSource()
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 163, in _getDataSource
    database = DataBase(self._ctx, self._logger, url)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/database.py", line 71, in __init__
    connection = getDataBaseConnection(ctx, url, user, pwd, new)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbinit.py", line 82, in getDataBaseConnection
    infos = getDriverInfos(ctx, url, g_drvinfos)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbtool/dbtool.py", line 807, in getDriverInfos
    for name, value in _getDriverPropertyInfo(ctx, location, properties, options):
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbtool/dbtool.py", line 814, in _getDriverPropertyInfo
    drivers = createService(ctx, service).createEnumeration()
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/unotool/unotool.py", line 344, in createService
    service = ctx.ServiceManager.createInstanceWithContext(name, ctx)
```

Once again, is the window **OAuth2OOo - Demande d'autorisation** displayed and are there any messages in the console?

Also, it seems to me that your window: **file -> open** is a system window and not the internal file picker window of LibreOffice. Normally it should look like this:

![gDriveOOo file open](https://github.com/user-attachments/assets/8bb975b2-4665-4770-9c94-618ff9b3bfa8)
Moreover, if this is the case, **it means that the gDriveOOo extension is not installed**.

And what about the `libreoffice-base-driver` package?

Without more help from you it will be difficult to move forward...

**Comment by jcvignoli** [comment]
Hi,

1. The console message is slighty different, an extra line is added:
```
Exception python inattendue avec le traceback: Traceback (most recent call last):
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 110, in queryContent
    content = self._datasource.queryContent(self, self._authority, url)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 97, in _datasource
    ContentProvider.__datasource = self._getDataSource()
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/contentprovider.py", line 163, in _getDataSource
    database = DataBase(self._ctx, self._logger, url)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/database.py", line 71, in __init__
    connection = getDataBaseConnection(ctx, url, user, pwd, new)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbinit.py", line 83, in getDataBaseConnection
    return getDataSourceConnection(ctx, url, user, pwd, new, infos)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbtool/dbtool.py", line 117, in getDataSourceConnection
    datasource = getDataSource(ctx, url)
  File "/home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/service/pythonpath/gdrive/dbtool/dbtool.py", line 137, in getDataSource
    datasource = dbcontext.getByName(location)
gdrive.dbtool.dbtool.com.sun.star.lang.WrappedTargetException: file:///home/user/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu67451d6et.tmp_/gDriveOOo.oxt/hsqldb/vnd-google.odb

```

2. There is no "window OAuth2OOo - Demande d'autorisation" displayed when I enter "vnd-google:///"
3.  "it seems to me that your window: file -> open is a system window" Unless I'm mistaken, our windows are exactly the same, but you seem to use kde. I use gnome.
4. Regarding the "libreoffice-base-drivers" packages, I followed your instructions. Installed and removed the hq packages.

**Comment by prrvchr** [comment]
> it seems to me that your window: file -> open is a system window" Unless I'm mistaken, our windows are exactly the same, but you seem to use kde. I use gnome

I don't see your window completely, the top is missing...
On the other hand, you have to enter `vnd-google:///` **in the first field** (ie: the top one like my screenshot) of the window and not in:  `Nom de fichier`, **and confirm the entry by pressing the enter key**.

> Regarding the "libreoffice-base-drivers" packages, I followed your instructions. Installed and removed the hq packages.

I think this problem prevented the database creation that is done when gDriveOOo is first launched, and probably left it in an unusable state. It is imperative to uninstall gDriveOOo, restart LibreOffice properly (ie: see the recommendations on this point) and reinstall gDriveOOo.

> There is no "window OAuth2OOo - Demande d'autorisation" displayed when I enter "vnd-google:///"

This will not be able to go further without displaying this window.

**Comment by jcvignoli** [comment]
> On the other hand, you have to enter vnd-google:/// in the first field (ie: the top one like my screenshot) of the window and not in: Nom de fichier, and confirm the entry by pressing the enter key.
I tried in both fields. I followed your suggestions.

> It is imperative to uninstall gDriveOOo, restart LibreOffice properly (ie: see the recommendations on this point) and reinstall gDriveOOo.
I did so. Seems like the message changed:
```
ContentProvider.__init__()
LoggerPool.__init__() *******************************
LoggerPool._getNamedLogger() io.github.prrvchr.gDriveOOo.gDriveLog
ContentProvider.__init__() 1 Scheme: vnd-google
ContentProvider.__init__() 2 Scheme: vnd-google
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 4
```

> This will not be able to go further without displaying this window.
I tried to enter manually the OAth2OOo (in tools - internet - OAth2 protocol), seems it successfully registered (according to the log        `5   112464 2024-10-26 22:34:23.665086959 OAuth2Service::getAuthorization(): Request Authorization ... Authorization has been granted...`). Doesn't change anyhting when entering vnd-google:///.
I guess this conclude the debugging, thanks for trying.

**Comment by prrvchr** [comment]
```
ContentProvider.__init__()
LoggerPool.__init__() *******************************
LoggerPool._getNamedLogger() io.github.prrvchr.gDriveOOo.gDriveLog
ContentProvider.__init__() 1 Scheme: vnd-google
ContentProvider.__init__() 2 Scheme: vnd-google
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 4
```

You are not giving me the right information.

This is what is displayed on the console if I launch LibreOffice from a terminal with the `soffice` command until the authorization request for the OAuth2OOo extension is displayed.

[gDriveOOo console.txt](https://github.com/user-attachments/files/17532223/gDriveOOo.console.txt)

There are almost 4000 lines!!! so what can i do with 8 lines?

It doesn't matter, I think I'll close...

**Comment by jcvignoli** [comment]
> There are almost 4000 lines!!! so what can i do with 8 lines?

Man, that's all the lines I get. I understand you're frustrated, but the way you talk to me is terrible.
Bonne continuation, et bonne apprentissage du support avec des personnes qui passent autant de temps à te fournir des informations.

**Comment by prrvchr** [comment]
Normalement sous Linux il est très facile d'identifier les problèmes en utilisant la console, en fait c'est la console qui nous a permis de voir que LibreOffice n'était pas installé correctement (le paquet libreoffice-base-driver était manquant ou mal installé...) mais comment faire sans ces informations?

Alors je préfère dire à l'impossible nul n'est tenu...
