### ISSUE TITLE
Error connecting to vnd.google-apps:///

### ISSUE THREAD

**Issue by ghost** [prrvchr/gDriveOOo#2]
"Nonexistent object.
Nonexistent file."
This error happens when I try to open the gdrive location, even though it said that it was safe to close the gDriveOOo webpage.

**Comment by prrvchr** [comment]
Hi Cyberman113,
i just updated the repository, i think you can do some new tests and tell me if i can close this issue.
Thank you.
Edit: you have to reinstall all the components (OAuth2OOo, CloudUcpOOo and gDriveOOo)

**Comment by funihao** [comment]
Hello!
It doesn't work.
I have uninstalled the three macros and reinstalled all components (OAuth2OOo, CloudUcpOOo and gDriveOOo).
It gives the same error.
LibreOffice Versión: 6.2.3.2

![gDrive-error](https://user-images.githubusercontent.com/9009902/58278009-54f11780-7d9b-11e9-989a-f3e6da619fe7.png)

**Comment by prrvchr** [comment]
Hi funihao,
The integration of Dropbox has required the modification of OAuth2OOo and CloudUcpOOo.
It's now done and I have 3 providers (gDrive, oneDrive and Dropbox) that works for me.

Please reinstall the latest version, taking care to uninstall before any update.

Thank to keep me informed.

EDIT: I confirm that it does not work under Windows, I look and tell you...

**Comment by prrvchr** [comment]
Hi,
The problem does not come from Window but from LibreOffice ...

It is necessary to add the JDBC Driver (archive jar) to the User Class Path as described in [README.md](https://github.com/prrvchr/CloudUcpOOo/blob/master/README.md)

Before any test, please reinstall the latest version taking care to uninstall before any update.

**Comment by zdens** [comment]
hi all,
I faced with this problem too, but I don't see any words about JDBS Driver in

> It is necessary to add the JDBC Driver (archive jar) to the User Class Path as described in README.md

**Comment by prrvchr** [comment]
This issue is obsolete since:
- now Hsqldb 2.5.x is used
- in LibreOffice the workaround is to not install the Hsqldb driver (1.8.x) during the installation of LibreOffice
Please reopen a new issue if necessary.
