### ISSUE TITLE
Cannot install gDriveOOo extension

### ISSUE THREAD

**Issue by swissk** [prrvchr/gDriveOOo#3]
Hello,

Everytime I try to install gDriveOOo extension into Libreoffice 6.3.4.2 I get an error from urllib3, on Debian 10. 
Have try to correct the error by installing python3. 
python3: can't open file 'setup.py': [Errno 2] No such file or directory
Any ideas on what can I do?
Thanks in advance

**Comment by prrvchr** [comment]
Hi swissk,

I am not under Debian but under Lubuntu and install LibreOffice from a PPA:
[LibreOffice PPA](http://ppa.launchpad.net/libreoffice/ppa/ubuntu)
In any case, check if you have installed `python3-uno` package...

**Comment by prrvchr** [comment]
Hi swissk,
Tell me if it works as expected?
Without answer in a few days, I will allow myself to close this issue....
Thank

**Comment by prrvchr** [comment]
Without response, I close the issue...
