### ISSUE TITLE
gdriveoo installation exits with error

### ISSUE THREAD

**Issue by swissk** [prrvchr/gDriveOOo#4]
Hello prrvchr,

Libreoffice 6.4 installed directly from the latest deb package under Debian 10. I do have python3-uno installed. Still Gdriveoo installation exits with an error. Attached is the screenshot of the full error. 

Best regards

PS. Sorry for not getting back to you before, but with gmail sorting the emails I did not see yours.

![oogdrive](https://user-images.githubusercontent.com/26161369/74602213-af0ed700-50a6-11ea-909a-f2a977b803c0.png)

**Comment by prrvchr** [comment]
Hi swissk,

can you confirm that you have installed the latest version, namely:
- [OAuth2OOo](https://github.com/prrvchr/OAuth2OOo/raw/master/OAuth2OOo.oxt)

and:
- [gDriveOOo](https://github.com/prrvchr/gDriveOOo/raw/master/gDriveOOo.oxt)

Taking care to respect the order of installation of the extensions, it is important...
Please confirm, I will do more investigations if necessary...

Edited: A regression coming with LibreOffice 6.4.x has just been corrected, the links to the relevant versions have been updated.

**Comment by prrvchr** [comment]
Hi swissk,

A new version [gDriveOOo v0.0.5](https://github.com/prrvchr/gDriveOOo/raw/master/gDriveOOo.oxt) is available.

This new version is now compatible with LibreOffice 6.4.X and 7.X.

Can you make tests with this new version and open a new issue if necessary.

**Comment by swissk** [comment]
Hi prrvch,

I have tried to install new version gDriveOOo v0.0.5, but keep getting an error message. "Cannot import name 'logMessage' from 'gdrive'". 

I deleted previous version and tried installing, but same error pops-up.
