### ISSUE TITLE
Cannot save file to Drive

### ISSUE THREAD

**Issue by CatoMaior** [prrvchr/gDriveOOo#5]
Thanks for your work, very useful. I can open and edit files with no problems, but i cannot save files to Drive. I see there is a similar issue closed, but I think the problem is not solved. See the attached error message.
![Screenshot from 2020-02-29 22-02-19](https://user-images.githubusercontent.com/40829361/75615146-91c71780-5b40-11ea-8018-938ececd8082.png)

**Comment by prrvchr** [comment]
Hi CatoMaior,

I think you don't put your user account in the url.
If this is the case can you try with the user account in the url (ie: vnd.google-apps://your_account@gmail.com/)
Thanks

**Comment by CatoMaior** [comment]
Thanks. I tried and it doesn't work even with my user account in the url. See log attached
[com.gmail.prrvchr.extensions.gDriveOOo.Logger.log](https://github.com/prrvchr/gDriveOOo/files/4271741/com.gmail.prrvchr.extensions.gDriveOOo.Logger.log)

**Comment by CatoMaior** [comment]
Sorry for the open-close, I misclicked

**Comment by prrvchr** [comment]
Hi CatoMaior,

A new version [gDriveOOo v0.0.5](https://github.com/prrvchr/gDriveOOo/raw/master/gDriveOOo.oxt) is available.

I think it fixes most of the issues encountered with previous version.

Can you make tests with this new version and open a new issue if necessary.
