### ISSUE TITLE
Can"t see anything

### ISSUE THREAD

**Issue by drsnn** [prrvchr/gDriveOOo#6]
Hi 

i installed liber office 7 beta . I  authorized the OAuthOOo application  to my gDrive. I also installed gDriveoo extension. But i cant see my drive under places. When i try to click to the server option, a file service opened and ask me my gdrive id and password but after i enter it it ask for 6 digit pin. So i couldnt Save my files to drive. 

Could you help me?

**Comment by prrvchr** [comment]
Hi drsnn,

A new version [gDriveOOo v0.0.5](https://github.com/prrvchr/gDriveOOo/raw/master/gDriveOOo.oxt) is available. Now it works with LibreOffice 6.4.X and 7.X.

Can you make tests with this new version and open a new issue if necessary.
