### ISSUE TITLE
gDriveOOo exits with error when trying to install it. "Cannot import name 'logMessage' from 'gdrive"

### ISSUE THREAD

**Issue by swissk** [prrvchr/gDriveOOo#7]
Hi prrvchr,

Have not been able to test new version of gDriveOOo v0.0.5, I keep getting an error message. "Cannot import name 'logMessage' from 'gdrive".

I deleted previous version and tried a fresh install, but same error pops-up.

I switched from Java version Debian 11.0.8 to Oracle Co. 1.8.0.201, did not change anything. 

![gDriveOOo](https://user-images.githubusercontent.com/26161369/89530553-fc1a6d00-d7ee-11ea-87a3-4bebfd59b03a.png)

Let me know how I can help.

**Comment by prrvchr** [comment]
Hi swissk,
I just push new revision of [OAuth2OOo](https://github.com/prrvchr/OAuth2OOo/raw/master/OAuth2OOo.oxt) and [gDriveOOo](https://github.com/prrvchr/gDriveOOo/raw/master/gDriveOOo.oxt) oxt.
Can you do a test with these new revisions and tell me if it works.
Your Java version  Debian 11.0.8 or Oracle Co. 1.8.0.201  are both good...
Thank you

**Comment by prrvchr** [comment]
Please keep me informed, even if it works, that I can close the issue

No answer, so I close ...
