### ISSUE TITLE
Objet n'existe pas - Fichier inexistant

### ISSUE THREAD

**Issue by BOULLAND** [prrvchr/gDriveOOo#8]
Bonjour,
J'ai suivi la mise oeuvre pas à pas.
Lorsque je lance ouverture fichier avec vnd.google-apps:/// ; j'obtiens " l'objet n'existe pas - fichier inexistant".
Quelle serait la cause possible de cette erreur.
Cordialement

**Comment by prrvchr** [comment]
Bonjour [BOULLAND](https://github.com/BOULLAND),

Merci de participer aux tests cela aide à améliorer les extensions.

De nombreux changements ont été apportés depuis l'ouverture de ce problème, voir le [dysfonctionnement oneDrive OOo #5](https://github.com/prrvchr/oneDriveOOo/issues/5)

Je ferme ce sujet, vous devrez en ouvrir un autre si le problème persiste.
