### ISSUE TITLE
utilisation de gDriveOOo extension non fonctionnel

### ISSUE THREAD

**Issue by Louislix** [prrvchr/gDriveOOo#9]
Sur un PC sous **Kubuntu** 20.10 + Kde Plasma 5.19.5 + LibreOffice 7.2. Ai suivi l'installation préconisée  à https://prrvchr.github.io/gDriveOOo/README_fr.html  Après l'installation des extensions préconisées j'ai pu me connecter sur google drive grâce à la commande vnd.google-apps:///  Super
Par contre sur un 2° PC lui sous **Ubuntu** 20.10 + Kde Plasma 5.19.2 + LibreOffice 7.2 ayant suivi la même procédure de connexion je n'arrive pas à me connecter !!!!! J'imagine qu'il s'agit d'un fichier de configuration différent mais je ne trouve pas la clé. 

Merci de me dire si vous avez un éclairage ou une recommendation. 

Louis Delmas
louis.rene.delmas@gmail.com

**Comment by prrvchr** [comment]
Bonjour [Louislix](https://github.com/Louislix),

Merci de participer aux tests cela aide à améliorer les extensions.

De nombreux changements ont été apportés depuis l'ouverture de ce problème, voir le [dysfonctionnement oneDriveOOo #5](https://github.com/prrvchr/oneDriveOOo/issues/5)

Je ferme ce sujet, vous devrez en ouvrir un autre si le problème persiste.
